import type { Metadata } from "next";
import { IBM_Plex_Mono, League_Spartan } from "next/font/google";
import "./globals.css";

const geometricSans = League_Spartan({
  variable: "--font-geometric-sans",
  subsets: ["latin"],
});

const mono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geometricSans.variable} ${mono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
